repo_token: Wf9dalIovoj7oj8awapq4k4BGkeJd9pMk
[![Coverage Status](https://coveralls.io/repos/andela-bebowe/enigma_gem/badge.svg?branch=temp&service=github)](https://coveralls.io/github/andela-bebowe/enigma_gem?branch=temp)